{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dex-http-server.fullname" . }}
  labels:
    {{- include "dex-http-server.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: ["clusterrolebindings"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dex-http-server.fullname" . }}-cluster
  labels:
    {{- include "dex-http-server.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "dex-http-server.fullname" . }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "dex-http-server.serviceAccountName" . }}
{{- end }}
