---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dex-http-server
  namespace: mke
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dex-http-server
rules:
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: ["clusterrolebindings"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex-http-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dex-http-server
subjects:
  - kind: ServiceAccount
    name: dex-http-server
    namespace: mke
---
apiVersion: v1
kind: Service
metadata:
  name: dex-http-server
  namespace: mke
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: dex-http-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dex-http-server
  namespace: mke
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx-default
  rules:
    - http:
        paths:
          - backend:
              service:
                name: dex-http-server
                port:
                  number: 80
            path: /api/dex(/|$)(.*)
            pathType: Prefix
  tls:
    - hosts:
        - example.com
      secretName: auth-https.tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex-http-server
  namespace: mke
  labels:
    app: dex-http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex-http-server
  template:
    metadata:
      labels:
        app: dex-http-server
    spec:
      containers:
        - name: dex-http-server
          image: ghcr.io/mirantiscontainers/dex-http-server:dev
          args:
            - --grpc-server=authentication-dex:5557
            - --http-port=8080
            - --grpc-certs-path=/etc/dex-grpc-certs
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: dex-grpc-certs
              mountPath: /etc/dex-grpc-certs
              readOnly: true
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
      serviceAccountName: dex-http-server
      volumes:
        - name: dex-grpc-certs
          secret:
            secretName: auth-grpc.tls
---
apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
  namespace: mke
spec:
  volumes:
    - name: dex-grpc-certs
      secret:
        secretName: auth-grpc.tls
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: dex-grpc-certs
          mountPath: /etc/dex-grpc-certs
          readOnly: true
  hostNetwork: true
  dnsPolicy: Default
