openapiOptions:
  file:
    # the file name must be the same as one passed to protoc when generating .swagger.yaml
    - file: "api.proto"
      option:
        info:
          title: Dex HTTP API
          version: "1.0"
        tags:
          - name: Dex
            description: Dex HTTP API to manage users
        schemes:
          - HTTPS
        consumes:
          - application/json
        produces:
          - application/json
        responses:
          "401":
            description: Returned when the user does not provide authentication using Bearer token.
          "403":
            description: Returned when the user does not have permission to access the resource.
        securityDefinitions:
          security:
            ApiKeyAuth:
              type: TYPE_API_KEY
              name: Authorization
              in: IN_HEADER
        security:
          - securityRequirement:
              ApiKeyAuth: {}
