name: Merge

on:
  push:
    branches:
      - main

jobs:
  vet:
    uses: ./.github/workflows/vet.yml
  static-analysis:
    uses: ./.github/workflows/static-analysis.yml
  # unit-test:
  #   uses: ./.github/workflows/unit.yml
  build:
    needs: [vet, static-analysis]
    uses: ./.github/workflows/build.yml
  push-to-ghcr:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} # if all `needs` jobs are successful
    needs: [build]
    secrets: inherit
    uses: ./.github/workflows/push-to-ghcr.yml
  cleanup:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} # if all `needs` jobs are successful
    needs: [build]
    secrets: inherit
    uses: ./.github/workflows/cleanup.yml
