name: PR

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
    branches: [ "main" ]
    paths:
      - '**' # all files otherwise excludes wont work
      - '!**/**/*.md' # ignore markdown files

jobs:
  vet:
    uses: ./.github/workflows/vet.yml
  unit-test:
    uses: ./.github/workflows/unit.yml
  build:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} # if all `needs` jobs are successful
    needs: [vet, unit-test]
    secrets: inherit
    uses: ./.github/workflows/build.yml
  cleanup:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} # if all `needs` jobs are successful
    needs: [build]
    secrets: inherit
    uses: ./.github/workflows/cleanup.yml
