name: Release

on:
  release:
    types: [prereleased]

jobs:
  vet:
    uses: ./.github/workflows/vet.yml
  unit-test:
    uses: ./.github/workflows/unit.yml
  build:
    needs: [vet, unit-test]
    secrets: inherit
    uses: ./.github/workflows/build.yml
  push-to-ghcr:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} # if all `needs` jobs are successful
    needs: [build]
    secrets: inherit
    uses: ./.github/workflows/push-to-ghcr.yml
  push-helm-chart:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} # if all `needs` jobs are successful
    name: Push Helm chart
    needs: [push-to-ghcr]
    uses: ./.github/workflows/publish-helm-chart.yaml
    secrets: inherit
  cleanup:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} # if all `needs` jobs are successful
    needs: [push-helm-chart]
    secrets: inherit
    uses: ./.github/workflows/cleanup.yml
